export const GET_LAUNDRY_LIST = 'GET_LAUNDRY_LIST';
export const LAUNDRY_LIST_SUCCESS = 'LAUNDRY_LIST_SUCCESS';
export const LAUNDRY_LIST_FAILED = 'LAUNDRY_LIST_FAILED';
export const LAUNDRY_INFO_SUCCESS = 'LAUNDRY_INFO_SUCCESS';