const VendorServiceActionTypes = {
  SERVICE_CREATE_START: "SERVICE_CREATE_START",
  SERVICE_CREATE_SUCCESS: "SERVICE_CREATE_SUCCESS",
  SERVICE_CREATE_FAILED: "SERVICE_CREATE_FAILED",
  SERVICE_START: "SERVICE_START",
  SERVICE_SUCCESS: "SERVICE_SUCCESS",
  SERVICE_FAILED: "SERVICE_FAILED",
};

export default VendorServiceActionTypes;
