const VendorRiderActionTypes = {
  RIDER_CREATE_START: "RIDER_CREATE_START",
  RIDER_CREATE_SUCCESS: "RIDER_CREATE_SUCCESS",
  RIDER_CREATE_FAILED: "RIDER_CREATE_FAILED",
  VENDOR_RAIDER_START: "VENDOR_RAIDER_START",
  RIDER_SUCCESS: "RIDER_SUCCESS",
  RIDER_FAILED: "RIDER_FAILED",
};

export default VendorRiderActionTypes;
